### ISSUE TITLE
Column values are incorrectly cast to ints

### ISSUE THREAD

**Issue by ryanalder** [cs361fall2018/project-nullptr#11]
Columns are being distinguished as characters in the original code, and are being passed to overlapsShips() as an integer from placeShip(). As a result, endCol is inaccurate and should instead be a character. Below is output of the values of these variables.

row == 4
col == D
endRow == 5
endCol == 70

**Comment by DanilaFe** [comment]
you can still do all the needed comparisons on it. This isn't really a big deal, but I'll fix it nonetheless.
