### ISSUE TITLE
Implement out of bounds ship notification

### ISSUE THREAD

**Issue by DanilaFe** [cs361fall2018/project-nullptr#3]
As per the second user story, the user should not be able place a ship out of bounds.

**Comment by DanilaFe** [comment]
FYI, since there's only one function for "placing ship", I will make a stub for this feature and you can implement it when you want.

**Comment by JacksGo** [comment]
Okay, sounds good.

**Comment by DanilaFe** [comment]
Should be close.

**Comment by JacksGo** [comment]
For thoroughness, closed by 5a3783d25588f3f1f1b5334c6a1905e1205436d6
