### ISSUE TITLE
Implement the Sonar attack.

### ISSUE THREAD

**Issue by DanilaFe** [cs361fall2018/project-nullptr#54]
The sonar attack reveals the content in an area on the opponent's board at a location specified by the player. Its use is restricted by #59. The approximate completion time for the sonar attack function itself should be approximately two hours, once verifying and test creation is complete.

**Comment by ryanalder** [comment]
Addressed in #65

**Comment by JacksGo** [comment]
Things that are currently the case:

1. This is done
1. I am tired.
