### ISSUE TITLE
Only allow moving the fleet twice.

### ISSUE THREAD

**Issue by DanilaFe** [cs361fall2018/project-nullptr#75]

**Comment by DanilaFe** [comment]
Perhaps we need some centralized way of knowing how many times each special (sonar, fleet move) can be done? Also, this depends on someone to make the actual fleet moving code.

**Comment by JacksGo** [comment]
A counter exclusively for fleet moves (in contrast with Daniel's proposal above), was comitted in 159764ebf330e8ccbfcc3912c0ad6dd9b5a3210b.
